PAHO_MQTT_DIR=$PWD/deps/paho.mqtt.c-1.3.11

export CPATH="$PAHO_MQTT_DIR/include:$CPATH"
export LD_LIBRARY_PATH="$PAHO_MQTT_DIR/lib:$LD_LIBRARY_PATH"
export CMAKE_PREFIX_PATH="$PAHO_MQTT_DIR:$CMAKE_PREFIX_PATH"
